### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Weik1** [Testzero-wz/analog#4]
[root@iz2ze3paasmtr91yja3vgwz analog]# python3 main.py
/usr/local/lib64/python3.6/site-packages/scipy/__init__.py:147: UserWarning: NumPy 1.14.5 or above is required for this version of SciPy (detected version 1.14.3)
  UserWarning)
          AnaLog
          Blog: <https://www.testzero-wz.com>
          Email: <testzero.wz@gmail.com>

[*] Logs had been loaded before.Type reload command to reload logs.
Traceback (most recent call last):
  File "main.py", line 14, in main
    controller = Controller(path)
  File "/root/test/analog/analog/bin/controller/controller.py", line 134, in __init__
    self.tfidfVector = TfidfVector(self.path, self.config)
  File "/root/test/analog/analog/bin/machine_learning/TfidfVector.py", line 22, in __init__
    self.__fit()
  File "/root/test/analog/analog/bin/machine_learning/TfidfVector.py", line 28, in __fit
    self.fit_vector = self.fit_transform(fit_list)
  File "/usr/local/lib64/python3.6/site-packages/sklearn/feature_extraction/text.py", line 1851, in fit_transform
    self._tfidf.fit(X)
  File "/usr/local/lib64/python3.6/site-packages/sklearn/feature_extraction/text.py", line 1437, in fit
    X = check_array(X, accept_sparse=('csr', 'csc'))
  File "/usr/local/lib64/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/sklearn/utils/validation.py", line 672, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 1000000)) while a minimum of 1 is required.
Found array with 0 sample(s) (shape=(0, 1000000)) while a minimum of 1 is required.

**Comment by Testzero-wz** [comment]
你好，analog需要一些正常的访问记录建设语料库，这些访问记录应该放在train.txt下。
这个报错没考虑到使用者仅使用统计功能的情况，目前简单地加了个判断，你可以重新pull更新一下，看看能不能解决此问题: )

**Comment by Weik1** [comment]
> 你好，analog需要一些正常的访问记录建设语言料库，这些访问记录应该放在train.txt下。
> 这个报错没考虑到使用者直接使用统计功能的情况，目前简单地加了个判断，你可以重新拉更新一下，看看能不能解决此问题：）

感谢大佬，确实可以运行了不过，第一次运行的时候还是会报 找不到这个文件 analog/analog/logs/file_log.log，我手动创建下就能运行了
![image](https://user-images.githubusercontent.com/34065927/113815692-338a5080-97a6-11eb-9027-c4e235626383.png)

**Comment by Testzero-wz** [comment]
好的，感谢issue
